### ISSUE TITLE
installed cauchy-mult but does not work

### ISSUE THREAD

**Issue by ChaiShiMei** [albertfgu/diffwave-sashimi#11]
I installed cauchy-mult following the description "going to extensions/cauchy/ and running `python setup.py install`.". 
But when I run the 'sashimi.py' to investigate its structure. This message shows again "CUDA extension for cauchy multiplication not found. Install by going to extensions/cauchy/ and running `python setup.py install`. This should speed up end-to-end training by 10-50%"
I installed pykeops==1.5 first.

**Comment by albertfgu** [comment]
That's strange. First, perhaps try uninstalling pykeops to be safe (I don't use it anymore). Second, check if the extension exists with `pip list | grep cauchy`. If it does, try reinstalling with `pip uninstall -y cauchy-mult && pip install .` (inside the extensions folder), and then check again if pip finds it. Then try opening a Python REPL and checking if you can import the extension (`import cauchy_mult`).

**Comment by ChaiShiMei** [comment]
Thank you. When I install cauchy in another workstation, I met this issure

`python setup.py install`

> running install
> running 
> 
> bdist_egg
> running egg_info
> writing cauchy_mult.egg-info/PKG-INFO
> writing dependency_links to cauchy_mult.egg-info/dependency_links.txt
> writing top-level names to cauchy_mult.egg-info/top_level.txt
> reading manifest file 'cauchy_mult.egg-info/SOURCES.txt'
> writing manifest file 'cauchy_mult.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_ext
> /home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py:788: UserWarning: The detected CUDA version (11.5) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
>   warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
> building 'cauchy_mult' extension
> Emitting ninja build file /home/ubuntu0/Downloads/YuTian/extensions/cauchy/build/temp.linux-x86_64-3.7/build.ninja...
> Compiling objects...
> Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> [1/1] /usr/bin/nvcc  -I/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/torch/include -I/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/torch/include/TH -I/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/torch/include/THC -I/home/ubuntu0/anaconda3/envs/rftorch/include/python3.7m -c -c /home/ubuntu0/Downloads/YuTian/extensions/cauchy/cauchy_cuda.cu -o /home/ubuntu0/Downloads/YuTian/extensions/cauchy/build/temp.linux-x86_64-3.7/cauchy_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -lineinfo --use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=cauchy_mult -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
> FAILED: /home/ubuntu0/Downloads/YuTian/extensions/cauchy/build/temp.linux-x86_64-3.7/cauchy_cuda.o 
> /usr/bin/nvcc  -I/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/torch/include -I/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/torch/include/TH -I/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/torch/include/THC -I/home/ubuntu0/anaconda3/envs/rftorch/include/python3.7m -c -c /home/ubuntu0/Downloads/YuTian/extensions/cauchy/cauchy_cuda.cu -o /home/ubuntu0/Downloads/YuTian/extensions/cauchy/build/temp.linux-x86_64-3.7/cauchy_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -lineinfo --use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=cauchy_mult -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
> /usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
>   435 |         function(_Functor&& __f)
>       |                                                                                                                                                 ^ 
> /usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
> /usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
>   530 |         operator=(_Functor&& __f)
>       |                                                                                                                                                  ^ 
> /usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
> ninja: build stopped: subcommand failed.
> Traceback (most recent call last):
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1746, in _run_ninja_build
>     env=env)
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/subprocess.py", line 512, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "setup.py", line 24, in <module>
>     cmdclass={'build_ext': BuildExtension})
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
>     return distutils.core.setup(**attrs)
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/distutils/dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
>     self.do_egg_install()
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
>     self.run_command('bdist_egg')
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
>     cmd = self.call_command('install_lib', warn_dir=0)
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
>     self.run_command(cmdname)
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
>     self.build()
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/distutils/command/install_lib.py", line 107, in build
>     self.run_command('build_ext')
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
>     _build_ext.run(self)
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/distutils/command/build_ext.py", line 340, in run
>     self.build_extensions()
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
>     build_ext.build_extensions(self)
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
>     self._build_extensions_serial()
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
>     self.build_extension(ext)
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
>     _build_ext.build_extension(self, ext)
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
>     depends=ext.depends)
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 571, in unix_wrap_ninja_compile
>     with_cuda=with_cuda)
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1424, in _write_ninja_file_and_compile_objects
>     error_prefix='Error compiling objects for extension')
>   File "/home/ubuntu0/anaconda3/envs/rftorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
>     raise RuntimeError(message) from e
> RuntimeError: Error compiling objects for extension

**Comment by albertfgu** [comment]
Your environment looks very out of date (e.g. python 3.7, pytorch 11.3)
